### ISSUE TITLE
Another usenix security 2018 paper on fuzzing

### ISSUE THREAD

**Issue by mjstalebi** [cpuu/awesome-fuzzing#1]
HI,

Thanks for your helpful list of tools and research projects on fuzzing.

I appreciate it if you also look at our paper and add it to your list:
Charm: Facilitating Dynamic Analysis of Device Drivers of Mobile Systems
https://www.usenix.org/conference/usenixsecurity18/presentation/talebi

In this paper, we made fuzzing of mobile devices' drivers more efficient and more reliable. 
All the tools we developed are open source and can be found here:
https://github.com/trusslab/charm

please let me know if you need more information about our work.

**Comment by cpuu** [comment]
I just did not find it because it searches for 'fuzz' in the paper title.
Thank you for your feedback. 
Added to Usenix and tool(platform) section.

**Comment by mjstalebi** [comment]
Great! Thanks.
