### ISSUE TITLE
The link for "Favocado: Fuzzing the Binding Code of JavaScript
Engines Using Semantically Correct Test Cases" has an extra / at the end

### ISSUE THREAD

**Issue by AlekLefebvre** [cpuu/awesome-fuzzing#10]
https://www.ndss-symposium.org/wp-content/uploads/ndss2021_6A-2_24224_paper.pdf**/** should be https://www.ndss-symposium.org/wp-content/uploads/ndss2021_6A-2_24224_paper.pdf

**Comment by cpuu** [comment]
I updated, thanks you
