### ISSUE TITLE
Issues with fuzzers list and categorization

### ISSUE THREAD

**Issue by andreafioraldi** [cpuu/awesome-fuzzing#4]
Hi, there are several missing fuzzers in the list like the popular honggfuzz and AFLplusplus.
The categorization is broken.
For instance, libFuzzer is not a Binary fuzzer, but a source-level fuzzer. AFL supports both, source and binary.
Regards the Web/Javascript there are two independet categories merged.
The first, is the JS engines fuzzers like fuzzilli and CodeAlchemist, that are C/C++ source-level fuzzers made to test JS engines, the other are JS code fuzzer that are far away different (and less complex let me to say that) than JS engines fuzzers.

**Comment by andreafioraldi** [comment]
Ah and T-Fuzz is not a network protocol fuzzer but a binary-only fuzzer based on program transformation.

**Comment by cpuu** [comment]
Thank you for more information. You know a lot about the various tools. Can you suggest an appropriate category re-organization? In fact, I only check the paper, and I do not know exactly the tools that correspond to it.

**Comment by cpuu** [comment]
Since there has been no response for four years, I am closing this issue.
I have decided to reorganize according to the classification criteria found at https://fuzzing-survey.org/. 
The update will be carried out within a month.
